imports:
    - { resource: tables.yml }
services:
    dmzx.downloadlog.controller:
        class: dmzx\downloadlog\controller\downloadlog
        arguments:
            - '@template'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'
            - '@pagination'
            - '@controller.helper'
            - '@config'
            - '%dmzx.downloadlog.table.downloadlog%'
    dmzx.downloadlog.admin.controller:
        class: dmzx\downloadlog\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@language'
            - '@pagination'
            - '@cache'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.downloadlog.table.downloadlog%'
            - '%tables.attachments%'
    dmzx.downloadlog.listener:
        class: dmzx\downloadlog\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '%dmzx.downloadlog.table.downloadlog%'
        tags:
            - { name: event.listener }
